# Generated by Django 5.1.3 on 2025-01-27 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Coffeeroom', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltycard',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_cards', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='product',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Coffeeroom.branch', verbose_name='Филиал'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Coffeeroom.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='ikpu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coffeeroom.ikpu', verbose_name='ИКПУ'),
        ),
        migrations.AddField(
            model_name='sizeoption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_options', to='Coffeeroom.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='syrup',
            name='products',
            field=models.ManyToManyField(related_name='syrups', to='Coffeeroom.product', verbose_name='Продукты'),
        ),
    ]
