# Generated by Django 5.1.3 on 2025-01-27 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeeroom', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ikpu',
            options={'verbose_name': 'ИКПУ', 'verbose_name_plural': 'ИКПУ'},
        ),
    ]
