# Generated by Django 5.1.3 on 2025-01-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeeroom', '0003_alter_ikpu_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='packing_code',
            field=models.CharField(max_length=255, unique=True, verbose_name='Код упаковки'),
        ),
    ]
