# Generated by Django 5.1.3 on 2025-02-24 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeeroom', '0005_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='branch',
        ),
    ]
