# Generated by Django 5.1.3 on 2025-01-27 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Coffeeroom', '0002_initial'),
        ('Order', '0001_initial'),
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.cart', verbose_name='Корзина'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coffeeroom.product', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='syrup',
            field=models.ManyToManyField(blank=True, to='Coffeeroom.syrup', verbose_name='Сиропы'),
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.address', verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
        migrations.AddField(
            model_name='order',
            name='loyalty_card',
            field=models.ForeignKey(blank=True, help_text='Выберите лояльную карту для оплаты (если используется).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Coffeeroom.loyaltycard', verbose_name='Лояльная карта'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.paymentmethod', verbose_name='Способ оплаты'),
        ),
    ]
