# Generated by Django 5.1.3 on 2025-02-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeeroom', '0004_alter_product_packing_code'),
        ('Order', '0005_remove_cartitem_syrup_remove_order_loyalty_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='syrups',
            field=models.ManyToManyField(to='Coffeeroom.syrup', verbose_name='Сиропы'),
        ),
    ]
