# Generated by Django 5.1.3 on 2025-02-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeeroom', '0004_alter_product_packing_code'),
        ('Order', '0006_cartitem_syrups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='syrups',
            field=models.ManyToManyField(blank=True, to='Coffeeroom.syrup', verbose_name='Сиропы'),
        ),
    ]
