# Generated by Django 5.1.3 on 2025-02-03 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeeroom', '0004_alter_product_packing_code'),
        ('Order', '0007_alter_cartitem_syrups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='syrups',
            new_name='syrup',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size_option',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Coffeeroom.sizeoption', verbose_name='Опция размера'),
            preserve_default=False,
        ),
    ]
