# Generated by Django 5.1.3 on 2025-02-03 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0008_rename_syrups_cartitem_syrup_cartitem_size_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='syrup',
            new_name='syrups',
        ),
    ]
