# Generated by Django 5.1.3 on 2025-02-03 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0009_rename_syrup_cartitem_syrups'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Order.cart', verbose_name='Корзина'),
            preserve_default=False,
        ),
    ]
